name: autotest
on:
  push:
    branches:
      - main
      - Documentation
      - Test
      - Lib
  pull_request:
    branches:
      - main
      - Documentation
      - Test
      - Lib

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Установка Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3

      - name: Установка зависимостей
        run: |
          gem install bundler
          bundle install

      - name: Запуск тестов
        run: |
          bundle exec rspec
